### ISSUE TITLE
List of questions

### ISSUE THREAD

**Issue by badabam** [badabam/capstone-project-demo#1]
## Value statement
**As a** fullstack student `<user role>`
**I want to** have a list of coding questions `<desired function>`
**so that** I can learn the basics `<value/benefit>`

## Description (text, images,link to prototype)
<img width=50% src=https://user-images.githubusercontent.com/157286/208072509-0095e541-ae57-45f8-8883-8066db5419ba.png />

## Acceptance Criteria
- [x] Every question has exactly 1 right answer
- [x] Is only built for small screens (not responsive)

## Complexity (S, M, L)
- S

---

## Tasks

- [x] Create a feature branch
- [x] Define basic styles
- [x] Create `Card` component
- [x] Add styling for `Card`
- [x] Write test for `Card`
- [x] Add `Card` to the `App`
