### ISSUE TITLE
Selecting answers

### ISSUE THREAD

**Issue by badabam** [badabam/capstone-project-demo#2]
## Value statement
**As a** bootcamp student `<user role>`
**I want to** select an answer and see if it was right `<desired function>`
**so that** I can check my knowledge without being spoiled `<value/benefit>`

## Description (text, images,link to prototype)

![userstory2](https://user-images.githubusercontent.com/157286/208075833-97e63f91-6a0e-46ec-8612-aada7ecbf37a.png)

## Acceptance Criteria
- [ ] Answers are selected like radio buttons (only one can be checked)
- [ ] If the user clicks on `Check`,
  - [ ] the correct answer is highlighted in green
  - [ ] wrong answer is highlighted in red
  - [ ] Background of button is green / red pending on the result
- [ ] If no answer is selected, nothing happens
- [ ] On reload, everything is resetted

## Complexity (S, M, L)
M

---

## Tasks
- [ ] Create `Button` component
- [ ] Style `Button`
- [ ] Write test for `Button`
- [ ] Update `Card` component
- [ ] Update `Card` tests
- [ ] Use a global state in `App` to track results
